prefer-workspace-packages: true
packages:
  # all packages in direct subdirs of packages/
  - 'packages/*'
  # all plugins in direct subdirs of plugins/
  - 'plugins/*'
  # all docs in direct subdirs of docs/
  - 'docs/*'
